CentreonTrap\Domain\Trap:
  properties:
    id:
      type: int
      groups:
        - 'trap_main'
    name:
      type: string
      groups:
        - 'trap_main'
    description:
      type: string
      groups:
        - 'trap_main'