jms_serializer:
  metadata:
    directories:
      CentreonDummy:
        namespace_prefix: "CentreonTrap\\Domain"
        path: '%kernel.root_dir%/../config/packages/serializer/CentreonTrap'

services:
  _defaults:
    public: false
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, controller...

  CentreonDummy\:
    resource: '../../../src/CentreonTrap/*'
